webtalk_init -webtalk_dir C:/Users/Dude/Desktop/BSUIR-Labs/7 term/APVMiS/Lab2/Lab2/Lab2/Lab2.sim/sim_1/behav/xsim/xsim.dir/lab2_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Oct 18 13:36:18 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "bc7a48ef-0043-42a6-9bc0-3149d2b6cbec" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "97b355c4b1eb4a948f3e894363725fc0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "15" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2112 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "5" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6420_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3836916337 -regid "" -xml C:/Users/Dude/Desktop/BSUIR-Labs/7 term/APVMiS/Lab2/Lab2/Lab2/Lab2.sim/sim_1/behav/xsim/xsim.dir/lab2_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Dude/Desktop/BSUIR-Labs/7 term/APVMiS/Lab2/Lab2/Lab2/Lab2.sim/sim_1/behav/xsim/xsim.dir/lab2_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Dude/Desktop/BSUIR-Labs/7 term/APVMiS/Lab2/Lab2/Lab2/Lab2.sim/sim_1/behav/xsim/xsim.dir/lab2_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
